fraywing/textAngular

- test/textAngular.spec.js
I hope this test gives you a better insight into the problem I was describing in issue #484.
Feel free to throw it away after you ran it, to adapt it, to ask me for more info, ...
I know I may not be following your PR and code style guides, but I'm just hoping to show you the issue more clearly
> Added a test to prove problems in issue #484

- src/textAngularSetup.js
> Fixed typo.

- bower.json
> Updates Rangy version to ~1.3.0

- src/main.js
I don't know why restoreSelection was being called at the point. But it broke some basic features of TA.
I tested everything and it didn't break anything else by removing it. Also the tests are OK.
> Fix to Issue #757

- Gruntfile.js
Grunt is looking in the wrong directory.  
This will fix it.
> fix(grunt): Update javascript path in watch target

- src/main.js
Create option for text-angular which makes it possible to lock aspect
ration for image resize. The option is "ta-image-resize-aspect-ratio"
> feature(textAngular): Fixed aspect ratio option for images resize

- src/textAngular-sanitize.js
> Update to add input in the element list

- Gruntfile.js
- src/demo/demo.html
- src/demo/static-demo.html
- src/demo/textAngular.com.html
* Add demo of textAngular to src
* Add grunt target to generate demo pages
* Update demo pages to reference newer version of angular and bootstrap
> Fix(demo Pages): Fix outdated demo of textAngular

- src/textAngularSetup.js
Seen a few requests for this, its a pretty simple implementation
> Add justifyFull to toolbar

- test/taToolFunctions.spec.js
The URL was actually valid, it should not be valid.
> chore(test): Fix failing unittest

- README.md
> Fix(Readme): Plunkr was not loading

- src/main.js
> Fix(main): tests weren't running without requireJS

- package.json
> Fix(package): There was two files as the main application file

- src/taBind.js
- src/textAngular-sanitize.js
- test/taBind/taBind.$formatters.spec.js
> feat(textAngular): Added support to maintain html comments and most white space!

- src/taBind.js
… paste.
TODO we need to clean up all this stuff and make it much better. Also the
paste of html in general is problimatic since the existing state of the
text is contaminated.
> fix(taBind.js): fixes #617 paste formatting problem

- Gruntfile.js
Compile demo pages was not being committed along with the release.
> Fix(gitcommit): Committing also demo html pages.

- src/main.js
- src/textAngular-sanitize.js
> fix(textAngular-sanitize): textAngular's internal model ignores style attr #854

- src/main.js
- test/textAngularManager.spec.js
Fixes #763.  There is another PR out that addresses this issue ( #940 ), but I believe my solution is slightly more elegant and has passing tests.
> fix(textAngularManager): Fixes #763

- src/taBind.js
- test/taBind/taBind.wordPaste.spec.js
> Fix pasting headings from word

- demo/demo.html
Fixes:
* An Editor with name "htmlcontent" already exists
* chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js net::ERR_FAILED
> Fixes errors in demo.html

- src/globals.js
- src/main.js
- src/taBind.js
- test/textAngular.spec.js
The was a major change to the way taBind detects blank html.  This also resolves many issues where
the model and the html view would be out of sync.  Also note that it may be helpful to clear your browser
cache to insure that all the code changes are up to date.
> Fix(main, taBind, globals, textAngular.spec): resolved many issues around html and model

- Gruntfile.js
- src/globals.js
- src/main.js
- test/textAngular.spec.js
- test/textAngularManager.spec.js
This makes it easy to add the textAngular version into the html.
> feat(main, testAngular.spec): Added a new directive text-angular-version

- dist/textAngular.js
- dist/textAngular.min.js
- dist/textAngular.umd.js
- src/main.js
small change to resolve #1276
Editor will focus when files are dropped, but not when text is dropped.
> Fix editor focussing when dropping text

- src/main.js
If these aren't cleaned up:
1. They are a memory leak
2. Some versions of Internet Explorer throw errors when you load textAngular, then unload it, then start scrolling.
> Cleanup event handlers that are placed on the window
