fraywing/textAngular

- bower.json
avoid the injection of the following line of code in index.html, for it is not needed any more:
`<script src="bower_components/rangy-official/rangy-selectionsaverestore.js"></script>`
it closes the issue #514
> chore: remove "rangy-official" from bower.json

- src/textAngularSetup.js
Updated word count and character count to use ng-bind instead of interpolation for the case where interpolation symbols are overridden. I ran into this issue where I am building an angular app that uses laravel for the api and to hand off views. Laravel uses {{ and }} for it's blade engine so I overrode angular's interpolation symbols which causes word and character count to not work with textAngular.
Example of my override:
ssApp.config(function interpolateConfig($interpolateProvider) {
$interpolateProvider.startSymbol('{[{').endSymbol('}]}');
});
> Updated word count and character count to use ng-bind instead of interpolation

- bower.json
Looking at current [requirements](https://github.com/fraywing/textAngular#requirements) and into [semver](https://github.com/npm/node-semver#caret-ranges-123-025-004) is not the same requirements. And while it's working well on flexible bower dependency resolving, it's not working for things like rails-assets.org.
> Set dependencies correctly

- lib/taBind.js
Fix for bug mentioned here fraywing/textAngular#518
> fix for polish programmers keyboard alt+z 

- src/textAngular.js
Simply changed where the ```.finally``` callback for a toolbar action promise was being set to make sure it doesn't get executed before any ```.then``` callback that set inside the toolbar action callback.
> Fixed issue #561: Deffered button action is not performed when editor loses focus

- lib/taBind.js
- src/textAngular.js
Simply and a little dirty fix. Detects parentless &lt;li&gt; items and gives them a &lt;ul&gt; ... &lt;/ul&gt; context.
> fixed issue #610: Parentless list elements with copy-paste

- bower.json
This removes the "bootstrap-css-only" dependency from textAngular so that people can choose the Bootstrap package they need, e.g., "bootstrap", "bootstrap-sass-official", "bootstrap-css-only", or whatever. See issues 649.
> Fix https://github.com/fraywing/textAngular/issues/649

- src/textAngularSetup.js
Right now textAngular defines the `src` attribute twice on the `<img>` created when adding a video. This removes the duplicate.
> Removed duplicate src attribute on videos

- src/taBind.js
This fixes image overlay not responding until some edit operation has been performed.
Fixes #777
> Fix(taBind): Reapply selector handles on focus

- src/main.js
When resizing an image, the mousedown event does not unbind after each
selection of image so after selecting a few images and then resizing,
all images selected will resize.  Forcing removal of all mousedown
events before the new event is bound resolves this as no other mousedown
event should be bound at this point.
> fix(textAngular): fix resize image issue

- src/main.js
Fix image size generated with popover buttons and resize handle.
Because mixing popover size buttons and resize handle can create some funky image sizes because of width and height html attributes is mixed with CSS width and height.
> fix(textAngular): Use CSS instead of html attributes to resize image. 

- src/textAngularSetup.js
angular returns an error when the cursor is not inside the editor. This happens when the `commonElement === <'#document'>`. 
this case should be escaped properly.
> handle corner case when commonElement is document.

- src/main.js
After popover is opened (IE: Image selection), it requires 2 clicks to
hide the popover.  If image is selected again to close popover then the
next popover either does not open or requires multiple clicks to open.
> fix(textAngular): fix popover requires 2 clicks to hide

- src/taBind.js
the <span...></span> entries when they are now NOT Apple-converted-space
spans.
> fix(taBind.js): Improved the fix to handle Apple-converted-space, so that we only remove

- src/main.js
Hiding the popover at the end of the resize makes more sense.  There are still issues under firefox -- the window does not repaint and so the model does not get updated immediately.  Clicking anywhere fixes this, but I am unclear as to why this happens.  It works fine under Chrome.  Also this is no worse than before!
> fix(main.js): we now hide the popover at the end of the image resize.

- Gruntfile.js
- package.json
- src/DOM.js
- src/main.js
- src/taBind.js
* Remove manual wrapper by `grunt-umd` which produces a clean UMD wrapper
- dependencies are not required at the start of the script, not in middle, deferred, `angular.run()`.
- Fix #1016
- Fix #1013
- Fix #892
* Remove reference to `window` when using rangy. The wrapper exposes `rangy` in the closure.
* Fix #853 : `rangy/lib/rangy-selectionsaverestore` exports `rangy` itself. There is no need to copy it in `rangy.saveSelection`, in fact it extends it!
* Modify the `main` in package.json for pointing to non-minified, UMD ready file, debugging will be easier.
> refactor(umd): Better support of UMD

- README.md
The links were outdated and textAngular-rangy.min.js was missing, but needs
to be included for textAngular to work
> docs(README.md): update links to cdnjs and jsdelivr

- README.md
Replace `a` with `an`
`Contributers` → `Contributors`
> Fix(readme): typos

- src/main.js
- test/textAngularManager.spec.js
- reorganized the code and moved var _toolbars -> var toolbarScopes
and moved it out into the service('textAngularManager) scope
- _registerToolbar() -> _registerToolbarScope() for clarity
- Most IMPORTANTLY unregisterToolbar() now removes the toolbarScope
which was a memory leak before.
- added getToolbarScopes() to enable testing
- added a new test to textAngularManager.spec to extercise the new code
for coverage.
> Fix(textAngularManager) leaking memory issue #1231

- src/textAngular-sanitize.js
- test/textAngularSanitize/sanitize.spec.js
Added support for font-style = italic. Bold and underline were present
except italic was missing.
> Support for font-style = italic and font-size = [size em/px/%] in sanitize function validStyles

- README.md
rangy-saveselection.js changed to rangy-selectionsaverestore.js (see [https://github.com/timdown/rangy/tree/master/lib](https://github.com/timdown/rangy/tree/master/lib)). Documentation was not up to date.
> fix: fixed reference to rangy file in main README

- src/DOM.js
- src/demo/demo.html
- src/demo/textAngular.com.html
- src/main.js
- src/taBind.js
- DOM, taBind: improved the getSelection() so that it no longer throws rangy errors.
If range.getSlection() erros it return undefined now.
Also getSelectionElement() returns undefined on error as well.
This eliminates a rare rangy invalid index error.
- demo.html is improved and it is easier to select non-minimized textAngular
sources.
- textAngular.com.html is improved and it is easier to select non-minimized
textAngular sources.
- main: now we use the proper 'none' for the display property instead of ''
> fix(DOM, main, taBind, demo.html, textAngular.com.html)
